CYCLE_MAX: 1 # maximum clock rate
DURATION: 60 # simulation duration in seconds
N_TRIALS: 1 # number of trials
N_MACHINES: 3 # number of machines
PROB_MSG_A: 1 # probability threshold of sending message to machine A (out of 10)
PROB_MSG_B: 1 # probability threshold of sending message to machine B
PROB_MSG_C: 8 # probability threshold of sending message to machine A, B (above this is probability of internal event)
BASE_PORT: 50050